In [2]:
import torch
from torch import Tensor

a = torch.eye(2)
b = torch.cat([a,-a])
b

/home/korene/studies/venv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[ 1.,  0.],
        [ 0.,  1.],
        [-1., -0.],
        [-0., -1.]])

In [6]:
pdist = torch.nn.PairwiseDistance()
rr = torch.cdist(b, b, p=2)
rr


tensor([[0.0000, 1.4142, 2.0000, 1.4142],
        [1.4142, 0.0000, 1.4142, 2.0000],
        [2.0000, 1.4142, 0.0000, 1.4142],
        [1.4142, 2.0000, 1.4142, 0.0000]])

In [7]:
pollen_kernel = lambda r: torch.exp(-r**2 / 1.5) / 6.81978
p = pollen_kernel(rr)
p

tensor([[0.1466, 0.0387, 0.0102, 0.0387],
        [0.0387, 0.1466, 0.0387, 0.0102],
        [0.0102, 0.0387, 0.1466, 0.0387],
        [0.0387, 0.0102, 0.0387, 0.1466]])